"""Export pending tag-audit proposals as a grouped review command script.

Reads data/eval/tag_audit.jsonl and writes data/eval/tag_review_commands.ps1:
one `review_tag_audit.py` invocation per pending row, grouped so the
direction-changing proposals (gold_wrong / detector_miss / spurious) come
first for line-by-line reading, followed by the bulk `justified` block.

This ONLY generates text — it never writes a verdict. The reviewer must read
each line (each is preceded by a comment with the transcript excerpt), edit
any proposal they disagree with, set $reviewer, then execute. Executing a line
is the explicit human sign-off that review_tag_audit.py records.

Usage:
    python scripts/export_tag_review_commands.py --reviewer xinanQ
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

AUDIT = Path("data/eval/tag_audit.jsonl")
OUT = Path("data/eval/tag_review_commands.ps1")

GROUP_ORDER = ["gold_wrong", "detector_miss", "spurious", "justified"]
GENERIC_NOTES = {"候选：对话可能展现该弱点，需逐条确认", "候选：可能是真实漏检，需逐条确认"}
DEFAULT_NOTE = {
    "justified": "复核transcript确认该弱点成立，gold漏标，同意补入",
    "detector_miss": "复核transcript确认弱点真实存在但未检出，保留失败入检测器backlog",
}


def _ps_quote(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reviewer", required=True, help="Reviewer name recorded on every executed line")
    args = parser.parse_args()

    rows = [json.loads(line) for line in AUDIT.read_text(encoding="utf-8").splitlines() if line.strip()]
    pending = [r for r in rows if r.get("review_status") != "human_reviewed"]
    groups: dict[str, list[dict]] = {g: [] for g in GROUP_ORDER}
    for row in pending:
        groups.setdefault(row.get("proposed_verdict") or "justified", []).append(row)

    lines = [
        "# Generated by scripts/export_tag_review_commands.py — READ BEFORE RUNNING.",
        "# Each executed line records YOUR explicit verdict (reviewer + note + timestamp).",
        "# Disagree with a proposal? Edit its --verdict/--note before running, or delete",
        "# the line and file it separately with scripts/review_tag_audit.py.",
        f"$py = \"C:\\Users\\Terre\\Desktop\\2026_Summer_intern\\ai陪练\\ai-coach-algorithm-W1\\.venv\\Scripts\\python.exe\"",
        f"$reviewer = {_ps_quote(args.reviewer)}",
        "",
    ]
    for group in GROUP_ORDER:
        items = groups.get(group) or []
        if not items:
            continue
        lines.append(f"# ===== {group} ({len(items)} rows) =====")
        for row in items:
            note = row.get("proposal_note") or ""
            if note in GENERIC_NOTES:
                note = DEFAULT_NOTE.get(group, note)
            excerpt = (row.get("transcript") or "")[:100].replace("\n", " ")
            lines.append(f"# {row['case_id']} / {row['kind']} / {row['tag']} | {excerpt}")
            lines.append(
                "& $py scripts/review_tag_audit.py"
                f" --case-id {row['case_id']}"
                f" --tag {_ps_quote(row['tag'])}"
                f" --kind {row['kind']}"
                f" --verdict {group}"
                f" --reviewer $reviewer"
                f" --note {_ps_quote(note)}"
            )
        lines.append("")

    # UTF-8 BOM so Windows PowerShell 5.1 reads the Chinese notes correctly.
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8-sig")
    counts = {g: len(groups.get(g) or []) for g in GROUP_ORDER}
    print(f"Wrote {sum(counts.values())} pending review commands to {OUT} (groups: {counts}); "
          f"{len(rows) - len(pending)} rows already human_reviewed were skipped.")


if __name__ == "__main__":
    main()
