USE stage_one;

-- Employee Mock Data
-- 表名：employees
-- 用途：保存员工基础信息，用于登录识别、机构归属、业绩上报、审核权限等功能测试
-- 机构层级对应关系：
-- 1 = CITY（南京市行）
-- 2 / 4 = BRANCH（鼓楼支行 / 玄武支行）
-- 3 / 5 / 6 / 7 / 8 = OUTLET（鼓楼营业室 / 珠江路网点 / 中央里网点 / 湖南路网点 / 新街口网点）

INSERT INTO employees
(`id`,
 `name`,
 `email`,
 `organization_id`,
 `age`,
 `department`,
 `position`,
 `level`,
 `is_new`,
 `work_type`,
 `is_admin`,
 `is_in_project`)

VALUES
    (1, '张明', 'zhangming@example.com', 2, 28, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (2, '侯烨晨', 'houyechen@example.com', 2, 31, '零售业务部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (3, '王晨', 'wangchen@example.com', 3, 24, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (4, '赵紫妍', 'zhaoziyan@example.com', 3, 35, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (5, '刘洋', 'liuyang@example.com', 1, 29, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (6, '李家慧', 'lijiahui@example.com', 1, 26, '个人金融部', '市行管理员', 'CITY', TRUE, '内勤', TRUE, TRUE),
    (7, '周航', 'zhouhang@example.com', 5, 38, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (8, '孙悦', 'sunyue@example.com', 5, 27, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, FALSE),
    (9, '林雨桐', 'linyutong@example.com', 1, 25, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (10, '韩子墨', 'hanzimo@example.com', 2, 33, '零售业务部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (11, '顾清扬', 'guqingyang@example.com', 2, 30, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (12, '唐思远', 'tangsiyuan@example.com', 2, 41, '营业部', '支行负责人', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (13, '许若溪', 'xuruoxi@example.com', 2, 27, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (14, '何嘉宁', 'hejianing@example.com', 2, 23, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (15, '宋一鸣', 'songyiming@example.com', 2, 36, '公司业务部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (16, '沈沐阳', 'shenmuyang@example.com', 2, 29, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (17, '叶知秋', 'yezhiqiu@example.com', 2, 32, '个人金融部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, FALSE),
    (18, '罗星辰', 'luoxingchen@example.com', 2, 26, '零售业务部', '理财经理', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (19, '魏嘉树', 'weijiashu@example.com', 2, 34, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (20, '江晚晴', 'jiangwanqing@example.com', 2, 28, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (21, '苏明哲', 'sumingzhe@example.com', 2, 39, '个人金融部', '支行负责人', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (22, '程安然', 'chenganran@example.com', 2, 24, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (23, '方语涵', 'fangyuhan@example.com', 2, 31, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (24, '邵景行', 'shaojingxing@example.com', 2, 35, '营业部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (25, '邓思琪', 'dengsiqi@example.com', 3, 26, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (26, '薛子昂', 'xueziang@example.com', 3, 37, '公司业务部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (27, '马若琳', 'maruolin@example.com', 3, 29, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (28, '秦浩然', 'qinhaoran@example.com', 3, 42, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (29, '丁可欣', 'dingkexin@example.com', 3, 25, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (30, '贺云川', 'heyunchuan@example.com', 1, 33, '公司业务部', '市行管理员', 'CITY', FALSE, '外勤', TRUE, TRUE),
    (31, '袁诗涵', 'yuanshihan@example.com', 3, 30, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (32, '夏知微', 'xiazhiwei@example.com', 3, 27, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, FALSE),
    (33, '钟立言', 'zhongliyan@example.com', 3, 38, '零售业务部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (34, '孟清欢', 'mengqinghuan@example.com', 3, 24, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (35, '梁景辰', 'liangjingchen@example.com', 3, 31, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (36, '乔安妮', 'qiaoanni@example.com', 3, 28, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (37, '傅云深', 'fuyunshen@example.com', 3, 35, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (38, '白嘉禾', 'baijiahe@example.com', 3, 23, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (39, '谭若星', 'tanruoxing@example.com', 3, 34, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (40, '覃曦南', 'qinxinan@example.com', 3, 40, '营业部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (41, '姜南风', 'jiangnanfeng@example.com', 4, 27, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (42, '莫雨薇', 'moyuwei@example.com', 4, 26, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (43, '邱泽宇', 'qiuzeyu@example.com', 4, 32, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (44, '段星河', 'duanxinghe@example.com', 4, 36, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (45, '任清越', 'renqingyue@example.com', 4, 29, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (46, '石沐辰', 'shimuchen@example.com', 4, 24, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (47, '崔雅楠', 'cuiyanan@example.com', 4, 31, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (48, '方可儿', 'fangkeer@example.com', 4, 39, '营业部', '支行负责人', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (49, '曹语晨', 'caoyuchen@example.com', 4, 28, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (50, '龚明轩', 'gongmingxuan@example.com', 4, 34, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, FALSE),
    (51, '侯若安', 'houruoan@example.com', 4, 25, '个人金融部', '理财经理', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (52, '朱景明', 'zhujingming@example.com', 4, 37, '营业部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (53, '毛嘉怡', 'maojiayi@example.com', 4, 30, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (54, '戴云熙', 'daiyunxi@example.com', 4, 23, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (55, '金书瑶', 'jinshuyao@example.com', 4, 33, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (56, '严修远', 'yanxiuyuan@example.com', 4, 41, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (57, '范思源', 'fansiyuan@example.com', 5, 26, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (58, '王铁柱', 'wangtiezhu@example.com', 5, 29, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (59, '余承恩', 'yuchengen@example.com', 5, 35, '个人金融部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (60, '倪浩岚', 'nihaolan@example.com', 5, 24, '营业部', '柜员', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (61, '钱沐白', 'qianmubai@example.com', 5, 32, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (62, '万景天', 'wanjingtian@example.com', 5, 38, '公司业务部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (63, '尹若雪', 'yinruoxue@example.com', 5, 27, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (64, '武星宇', 'wuxingyu@example.com', 5, 31, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, FALSE),
    (65, '龙嘉言', 'longjiayan@example.com', 5, 36, '零售业务部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (66, '程若曦', 'chengruoxi@example.com', 5, 25, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (67, '高云帆', 'gaoyunfan@example.com', 5, 33, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (68, '段嘉木', 'duanjiamu@example.com', 5, 28, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (69, '叶清宁', 'yeqingning@example.com', 5, 30, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (70, '沈星澜', 'shenxinglan@example.com', 5, 23, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (71, '顾云岚', 'guyunlan@example.com', 5, 34, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (72, '蒋子涵', 'jiangzihan@example.com', 5, 40, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (73, '周洛宁', 'zhouluoning@example.com', 2, 27, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (74, '韩清辞', 'hanqingci@example.com', 2, 29, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (75, '唐诗雨', 'tangshiyu@example.com', 2, 24, '个人金融部', '理财经理', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (76, '许嘉铭', 'xujiaming@example.com', 2, 35, '营业部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (77, '何思远', 'hesiyuan@example.com', 3, 31, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (78, '宋若晴', 'songruoqing@example.com', 3, 26, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (79, '沈书言', 'shenshuyan@example.com', 3, 33, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (80, '罗嘉宁', 'luojianing@example.com', 3, 39, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (81, '江若彤', 'jiangruotong@example.com', 4, 28, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (82, '苏景川', 'sujingchuan@example.com', 4, 36, '公司业务部', '支行管理员', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (83, '方一诺', 'fangyinuo@example.com', 4, 25, '个人金融部', '理财经理', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (84, '邵明朗', 'shaominglang@example.com', 4, 32, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, FALSE),
    (85, '马清欢', 'maqinghuan@example.com', 5, 27, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (86, '秦远航', 'qinyuanhang@example.com', 5, 34, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (87, '丁若兰', 'dingruolan@example.com', 5, 30, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (88, '何幸也', 'hexingye@example.com', 5, 38, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (89, '孟云舒', 'mengyunshu@example.com', 2, 23, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (90, '梁知夏', 'liangzhixia@example.com', 2, 31, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (91, '乔景和', 'qiaojinghe@example.com', 3, 29, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (92, '傅安然', 'fuanran@example.com', 3, 37, '营业部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (93, '白若初', 'bairuochu@example.com', 4, 26, '零售业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (94, '谭云起', 'tanyunqi@example.com', 4, 35, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (95, '陆嘉树', 'lujiashu@example.com', 5, 33, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (96, '姜星眠', 'jiangxingmian@example.com', 5, 24, '营业部', '柜员', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (97, '莫承宇', 'mochengyu@example.com', 2, 40, '零售业务部', '支行负责人', 'BRANCH', FALSE, '内勤', TRUE, TRUE),
    (98, '邱若辰', 'qiuruochen@example.com', 3, 28, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (99, '段清妍', 'duanqingyan@example.com', 4, 30, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (100, '任景澄', 'renjingcheng@example.com', 5, 36, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (101, '陈亦然', 'chenyiran@example.com', 1, 32, '运营管理部', '运营专员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (102, '林嘉禾', 'linjiahe@example.com', 1, 28, '公司业务部', '职员', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (103, '赵雨宁', 'zhaoyuning@example.com', 1, 35, '个人金融部', '业务专员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (104, '吴思源', 'wusiyuan@example.com', 1, 26, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (105, '徐安琪', 'xuanqi@example.com', 1, 30, '运营管理部', '职员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (106, '郑云川', 'zhengyunchuan@example.com', 1, 41, '风险合规部', '风险合规专员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (107, '胡若晨', 'huruochen@example.com', 1, 27, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (108, '许清言', 'xuqingyan@example.com', 1, 33, '个人金融部', '综合管理岗', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (109, '梁沐晴', 'liangmuqing@example.com', 1, 24, '零售业务部', '职员', 'EMPLOYEE', TRUE, '内勤', FALSE, FALSE),
    (110, '程嘉树', 'chengjiashu@example.com', 1, 29, '运营管理部', '职员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (111, '袁景然', 'yuanjingran@example.com', 6, 39, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (112, '高若彤', 'gaoruotong@example.com', 6, 34, '运营管理部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (113, '李思涵', 'lisihan@example.com', 6, 25, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (114, '周予安', 'zhouyuan@example.com', 6, 28, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (115, '孙明远', 'sunmingyuan@example.com', 6, 31, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (116, '马清扬', 'maqingyang@example.com', 6, 27, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (117, '王若曦', 'wangruoxi@example.com', 6, 24, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (118, '何云舟', 'heyunzhou@example.com', 6, 36, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, FALSE),
    (119, '唐安宁', 'tanganning@example.com', 6, 30, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (120, '宋景澜', 'songjinglan@example.com', 6, 33, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (121, '沈若楠', 'shenruonan@example.com', 6, 26, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (122, '罗承泽', 'luochengze@example.com', 6, 29, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (123, '叶安澜', 'yeanlan@example.com', 6, 32, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (124, '邓星辰', 'dengxingchen@example.com', 6, 23, '营业部', '职员', 'EMPLOYEE', TRUE, '内勤', FALSE, FALSE),
    (125, '顾明轩', 'gumingxuan@example.com', 7, 38, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (126, '韩若琳', 'hanruolin@example.com', 7, 35, '运营管理部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (127, '秦思远', 'qinsiyuan@example.com', 7, 27, '零售业务部', '职员', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (128, '丁语桐', 'dingyutong@example.com', 7, 24, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (129, '贺安琪', 'heanqi@example.com', 7, 29, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (130, '夏云帆', 'xiayunfan@example.com', 7, 31, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (131, '白清越', 'baiqingyue@example.com', 7, 26, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (132, '谭嘉宁', 'tanjianing@example.com', 7, 34, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (133, '江沐阳', 'jiangmuyang@example.com', 7, 28, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (134, '苏若辰', 'suruochen@example.com', 7, 25, '营业部', '职员', 'EMPLOYEE', TRUE, '内勤', FALSE, FALSE),
    (135, '方景行', 'fangjingxing@example.com', 7, 37, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (136, '邵云舒', 'shaoyunshu@example.com', 7, 30, '公司业务部', '职员', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (137, '莫知夏', 'mozhixia@example.com', 7, 23, '个人金融部', '理财经理', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (138, '邱嘉树', 'qiujiashu@example.com', 8, 40, '营业部', '网点负责人', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (139, '段若初', 'duanruochu@example.com', 8, 36, '运营管理部', '网点管理员', 'OUTLET', FALSE, '内勤', TRUE, TRUE),
    (140, '任云起', 'renyunqi@example.com', 8, 28, '零售业务部', '职员', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (141, '曹安然', 'caoanran@example.com', 8, 25, '公司业务部', '客户经理', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (142, '龚思琪', 'gongsiqi@example.com', 8, 30, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (143, '侯景明', 'houjingming@example.com', 8, 33, '营业部', '柜员', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE),
    (144, '朱若雪', 'zhuruoxue@example.com', 8, 26, '零售业务部', '职员', 'EMPLOYEE', TRUE, '外勤', FALSE, TRUE),
    (145, '毛星宇', 'maoxingyu@example.com', 8, 29, '公司业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (146, '戴嘉言', 'daijiayan@example.com', 8, 32, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, FALSE),
    (147, '金沐白', 'jinmubai@example.com', 8, 24, '营业部', '职员', 'EMPLOYEE', TRUE, '内勤', FALSE, TRUE),
    (148, '严景天', 'yanjingtian@example.com', 8, 35, '零售业务部', '客户经理', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (149, '范若溪', 'fanruoxi@example.com', 8, 27, '公司业务部', '职员', 'EMPLOYEE', FALSE, '外勤', FALSE, TRUE),
    (150, '余云帆', 'yuyunfan@example.com', 8, 31, '个人金融部', '理财经理', 'EMPLOYEE', FALSE, '内勤', FALSE, TRUE);